spring:
  application:
    name: mortgage-portal
  profiles:
    active: dev

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/housing-finance-mortgage
    username: postgres
    password: 0k0th985
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      idle-timeout: 30000
      max-lifetime: 60000

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true

  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
    table: schema_version

  # Kafka Configuration
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: mortgage-group
      auto-offset-reset: earliest
      enable-auto-commit: false

  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080}
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8080/.well-known/jwks.json}

#swagger-ui
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
  api-docs:
    path: /v3/api-docs

# AWS S3 Configuration
aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET:mortgage-documents}
    region: ${AWS_REGION:us-east-1}
    endpoint: ${AWS_S3_ENDPOINT:}
    access-key: ${AWS_ACCESS_KEY:}
    secret-key: ${AWS_SECRET_KEY:}

# JWT Configuration
jwt:
  secret-key: ${JWT_SECRET:your-256-bit-secret-change-this-for-production}
  expiration-time: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
  issuer: mortgage-portal
  secret: secretKeyForJWTSigningAndVerificationPurposesInTaskManagementSystem
  expiration: 86400000

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
    health:
      defaults:
        enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    metrics:
      access: unrestricted
    prometheus:
      access: unrestricted

# OpenTelemetry Configuration
opentelemetry:
  exporter:
    otlp:
      endpoint: ${OTLP_ENDPOINT:http://localhost:4317}
  resource:
    attributes:
      service.name: mortgage-portal

# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.okoth.mortgage: DEBUG
  file:
    name: logs/mortgage-portal.log

# Application Specific Configuration
mortgage:
  document:
    max-size-mb: 10
    allowed-types: application/pdf,image/jpeg,image/png
  application:
    default-page-size: 20
    max-page-size: 100

security:
  jwt:
    secret-key: your-256-bit-secret-change-this-for-production  # Use a strong secret in production
    expiration-time: 86400000  # 24 hours in milliseconds
    issuer: mortgage-portal

loan:
  application:
    limit: 20000