package com.okoth.mortgage.models.wsdl.transaction;

import com.okoth.mortgage.models.wsdl.ObjectFactory;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/** This class was generated by the JAX-WS RI. JAX-WS RI 2.3.2 Generated source version: 2.2 */
@WebService(name = "TransactionDataPort", targetNamespace = "http://credable.io/cbs/transaction")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ObjectFactory.class})
public interface TransactionDataPort {

  /**
   * @param transactionsRequest TransactionsRequest
   * @return returns com.okoth.credable.stubs.TransactionsResponse
   */
  @WebMethod(operationName = "Transactions")
  @WebResult(
      name = "TransactionsResponse",
      targetNamespace = "http://credable.io/cbs/transaction",
      partName = "TransactionsResponse")
  TransactionsResponse transactions(
      @WebParam(
              name = "TransactionsRequest",
              targetNamespace = "http://credable.io/cbs/transaction",
              partName = "TransactionsRequest")
          TransactionsRequest transactionsRequest);
}
